name: Setup on Linux
description: Setup basic conda and Python environment on Linux

inputs:
  mode:
    description: whether to install all dependencies
    required: true
    default: all

runs:
  using: composite
  steps:
    - name: install graphviz from apt
      run: sudo apt install -y graphviz graphviz-dev
      shell: bash
    - name: set path to dependencies
      id: set-dep-path
      run: |
        if [ ${{ inputs.mode == 'all' }} ]; then
          echo "::set-output name=dep-path::requirements/**/*.txt"
        elif [ ${{ inputs.mode == 'none' }} ]; then
          echo "::set-output name=dep-path::''"
        else
          echo "Wrong mode ${{ inputs.mode }}"
          exit 1
        fi
      shell: bash
    - name: set up Python with cache
      uses: actions/setup-python@v4
      id: py
      with:
        python-version: '3.10'
        # cache: 'pip'
        # cache-dependency-path: ${{ steps.set-dep-path.outputs.dep-path }}
    - run: echo "cache hit ${{ steps.py.outputs.cache-hit }}"
      shell: bash
    - name: install dependencies
      run: |
        if [ ${{ inputs.mode == 'all' }} ]; then
          bash requirements/install_all.sh
        fi
        echo "PYTHONPATH=$PYTHONPATH:${GITHUB_WORKSPACE}" >> $GITHUB_ENV
      shell: bash
